version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.17.0
    steps:
      - checkout
      - run:
          name: yarn install
          command: yarn --cwd functions/ install
      - run:
          name: yarn build
          command: yarn --cwd functions/ build
      - run:
          name: yarn lint
          command: yarn --cwd functions/ lint
  deploy:
    docker:
      - image: circleci/node:8.17.0
    steps:
      - run:
          name: deploy to Firebase Function
          command: functions/node_modules/.bin/firebase deploy --only functions --token=$FIREBASE_TOKEN

workflows:
  version: 2
  workflows:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only:
                - develop
                - master
