version: 2
jobs:
  yarn_install_for_clients:
    docker:
      - image: circleci/node:8.17.0
    steps:
      - checkout
      - restore_cache:
          key: yarn-clients-{{ .Branch }}-{{ checksum "clients/yarn.lock" }}
      - run:
          name: yarn install for clients
          command: yarn --cwd clients/ install
      - save_cache:
          key: yarn-clients-{{ .Branch }}-{{ checksum "clients/yarn.lock" }}
          paths:
            - ./clients/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  yarn_install_for_functions:
    docker:
      - image: circleci/node:8.17.0
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: yarn-functions-{{ .Branch }}-{{ checksum "functions/yarn.lock" }}
      - run:
          name: yarn install for clients
          command: yarn --cwd functions/ install
      - save_cache:
          key: yarn-functions-{{ .Branch }}-{{ checksum "functions/yarn.lock" }}
          paths:
            - ./functions/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    docker:
      - image: circleci/node:8.17.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: yarn lint
          command: |
            yarn --cwd functions/ lint
            yarn --cwd clients/ lint
      - run:
          name: yarn build
          command: |
            yarn --cwd functions/ build
            yarn --cwd clients/ build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: circleci/node:8.17.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: deploy to Firebase Function
          command: functions/node_modules/.bin/firebase deploy --only functions,hosting --token=$FIREBASE_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - yarn_install_for_clients
      - yarn_install_for_functions:
          requires:
            - yarn_install_for_clients
      - build:
          requires:
            - yarn_install_for_functions
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
